replicaCount: 2

images:
  webapp:
    repository: codeurjc/java-webapp-bbdd
    tag: v2
  pullPolicy: Always

service:
  type: NodePort
  port: 8080

env:
  mysql_root_password: pass
  mysql_database: test

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: www.carlosvegagarci.com
      paths: [/anuncios(/|$)(.*)]

  tls: []

metrics:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
